

name: 'Terraform'

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  terraform:
    name: 'Terraform'
    runs-on: windows-2019

    steps:
    # Checkout the repository to the GitHub Actions runner
    - run: Invoke-WebRequest -Uri https://youtube.com
